table_name: accounts

validation_rules:
  - column: account_id
    checks:
      - not_null
      - unique

  - column: customer_id
    checks:
      - not_null

  - column: branch_id
    checks:
      - not_null

  - column: account_type
    checks:
      - not_null
      - allowed_values:
          - SAVINGS
          - CURRENT

  - column: account_status
    checks:
      - not_null
      - allowed_values:
          - ACTIVE
          - INACTIVE

  - column: opened_date
    checks:
      - not_null
      - valid_date

  - column: updated_at
    checks:
      - not_null
      - valid_timestamp

  - column: is_deleted
    checks:
      - not_null
      - allowed_values:
          - true
          - false

